project:
  type: website
  output-dir: docs
website:
  title: "Can Cheap Sensors Help Us Monitor Nitrate in Rivers?"
  navbar:
    title: false
    left:
      - href: home.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: posts/index.qmd
        text: Blog
format:
  html:
    theme: cosmo
    css: styles.css


